### ISSUE TITLE
Crash when instanciating SimpleDialog

### ISSUE THREAD

**Issue by nalmada** [rey5137/material#119]
Version : 1.1.1

When i try to create a Simple Dialog by using 

```java 
SimpleDialog mDialog = new SimpleDialog(getApplicationContext(),R.style.SimpleDialog);
mDialog.title("Choisir Webservice").positiveAction("Paramètres").cancelable(false).show();"
```

I have an error at 
```java
SimpleDialog mDialog =  new SimpleDialog(getApplicationContext(),R.style.SimpleDialog);
```

There is the stacktrace : 

```java
05-21 11:45:40.637  21929-21929/com.example.isak.stockumgestionum E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.isak.stockumgestionum, PID: 21929
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.isak.stockumgestionum/com.example.isak.stockumgestionum.Login}: java.lang.RuntimeException: Failed to resolve attribute at index 13
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
     Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 13
            at android.content.res.TypedArray.getColorStateList(TypedArray.java:425)
            at android.content.res.XResources$XTypedArray.getColorStateList(XResources.java:1051)
            at com.rey.material.app.Dialog.applyStyle(Dialog.java:207)
            at com.rey.material.app.SimpleDialog.applyStyle(SimpleDialog.java:81)
            at com.rey.material.app.Dialog.init(Dialog.java:160)
            at com.rey.material.app.Dialog.<init>(Dialog.java:114)
            at com.rey.material.app.SimpleDialog.<init>(SimpleDialog.java:68)
            at com.example.isak.stockumgestionum.Login.loadPreferences(Login.java:72)
            at com.example.isak.stockumgestionum.Login.onCreate(Login.java:41)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
```

There is my sytle.xml : 

```xml
<resources>
     <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <item name="colorPrimary">@color/primary</item>
        <item name="colorPrimaryDark">@color/primary_dark</item>
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
        <item name="android:textColor">@color/primary_text</item>
        <item name="colorAccent">@color/black</item>
        <item name="searchViewStyle">@style/MySearchViewStyle</item>
        <item name="drawerArrowStyle">@style/MaterialDrawer.DrawerArrowStyle</item>
         <item name="material_drawer_background">@color/material_drawer_background</item>
         <item name="material_drawer_icons">@color/material_drawer_icons</item>
         <item name="material_drawer_primary_text">@color/material_drawer_primary_text</item>
         <item name="material_drawer_primary_icon">@color/material_drawer_primary_icon</item>
         <item name="material_drawer_secondary_text">@color/material_drawer_secondary_text</item>
         <item name="material_drawer_hint_text">@color/material_drawer_hint_text</item>
         <item name="material_drawer_divider">@color/material_drawer_divider</item>
         <item name="material_drawer_selected">@color/material_drawer_selected</item>
         <item name="material_drawer_selected_text">@color/primary_dark</item>
         <item name="material_drawer_header_selection_text">@color/material_drawer_header_selection_text</item>
         <!-- ActionMode (ContextMenu) style-->
        <item name="windowActionModeOverlay">true</item>
        <item name="actionModeBackground">@color/primary_dark</item>
     </style>
    <style name="SimpleDialog" parent="Material.App.Dialog.Simple">
        <item name="di_inAnimation">@anim/anim_scale_in</item>
        <item name="di_outAnimation">@anim/anim_scale_out</item>
    </style>
    <style name="cardTheme">
        <item name="selectableItemBackground">@drawable/card_ripple</item>
        <item name="android:selectableItemBackground">@drawable/card_ripple</item>
    </style>
    <style name="MyToolbarStyle" parent="ThemeOverlay.AppCompat.ActionBar">
        <!-- Used to for the title of the Toolbar -->
        <item name="android:textColorPrimary">@color/white</item>
        <!-- Used to for the title of the Toolbar when parent is Theme.AppCompat.Light -->
        <item name="android:textColorPrimaryInverse">@color/white</item>
        <!-- Used to color the text of the action menu icons -->
        <item name="android:textColorSecondary">@color/white</item>
        <!-- Used to color the overflow menu icon -->
        <item name="actionMenuTextColor">@color/white</item>
        <!-- Color of the Toolbar -->
    </style>
    <style name="MySearchViewStyle" parent="Widget.AppCompat.SearchView">
        <!-- Search button icon -->
        <item name="searchIcon">@drawable/ic_magnify_white_24dp</item>
        <item name="closeIcon">@drawable/ic_close_white_24dp</item>
    </style>
    <style name="MaterialDrawer.DrawerArrowStyle" parent="Widget.AppCompat.DrawerArrowToggle">
        <item name="spinBars">false</item>
        <item name="color">@android:color/white</item>
    </style>
</resources> 
```

Thanks,

**Comment by rey5137** [comment]
Seem like your app theme missing `colorControlActivated` item. The `Material.App.Dialog.Simple` style use this value for `di_actionTextColor`.

**Comment by nalmada** [comment]
Thanks ! 
adding 
```java
colorControlActivated 
```` 
to my style and replacing 
```java
SimpleDialog mDialog = new SimpleDialog(getApplicationContext(),R.style.SimpleDialog);
```
by 
```java
SimpleDialog mDialog = new SimpleDialog(Login.this,R.style.SimpleDialog); //Login is my activity
```
fix the problem.
