### ISSUE TITLE
orientationChange() dismiss dialog

### ISSUE THREAD

**Issue by jemshit** [rey5137/material#123]
Isn't there anyway to dimiss() dialog when orientation is changed ?? Because i'm getting NPE when i click positive button after screen orientation is changed. Code is:

```java
Dialog.Builder builder = new DatePickerDialog.Builder(){
                    @Override
                    protected Dialog onBuild(Context context, int styleId) {
                       ...
                        return super.onBuild(context, styleId);
                    }
                    @Override
                    public void onPositiveActionClicked(DialogFragment fragment) {
                       DatePickerDialog dialog = (DatePickerDialog)fragment.getDialog();
                       ...

                        }                      
                        super.onPositiveActionClicked(fragment);
                    }
                };
 builder.positiveAction(getString(R.string.ok));
 DialogFragment fragment = DialogFragment.newInstance(builder);
 fragment.show(getFragmentManager(), null);
```

Also i get this `WindowLeakage` in LogCat if dialog is showed and then orientation is changed.

```java
05-21 21:43:40.355  29077-29077/com.jemshit.itu E/WindowManager﹕ android.view.WindowLeaked: Activity com.jemshit.itu.ClassActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{42a1b400 G.E..... R.....ID 0,0-1920,1080} that was originally added here
            at android.view.ViewRootImpl.<init>(ViewRootImpl.java:457)
            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:267)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
            at android.app.Dialog.show(Dialog.java:289)
            at com.rey.material.app.Dialog.show(Dialog.java:623)
            at android.app.Dialog.onRestoreInstanceState(Dialog.java:433)
            at android.support.v4.app.DialogFragment.onActivityCreated(DialogFragment.java:388)
            at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1794)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:977)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1136)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1118)
            at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1927)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:544)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1177)
            at android.app.Activity.performStart(Activity.java:5461)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2367)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2452)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4035)
            at android.app.ActivityThread.access$1000(ActivityThread.java:172)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5586)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by jemshit** [comment]
@rey5137 can you check this?

**Comment by jemshit** [comment]
Changed 
```java 
DialogFragment fragment = DialogFragment.newInstance(builder);
 fragment.show(getFragmentManager(), null);
```
to
```java
DialogFragment fragment = DialogFragment.newInstance(builder);
 fragment.show(getFragmentManager(), "damnFragment");
``` 

and added
```java
 public void setUserVisibleHint(boolean visible){
        super.setUserVisibleHint(visible);
        if (visible && isResumed()){
            Fragment f= getFragmentManager().findFragmentByTag("damnFragment");
            if (f!= null) {
                DialogFragment df = (DialogFragment) f;
                df.dismiss();
                getFragmentManager().beginTransaction().remove(f).commit();
            }
    }
```

**Comment by candeiasdan** [comment]
This problem is not fixed. The solution provided be @jemshit does not solve the problem. 
I made these local changes on demo project, but the leaking problem still occurs.
