### ISSUE TITLE
Datepicker Rendering problem

### ISSUE THREAD

**Issue by raviteja786143** [rey5137/material#169]
Getting this error for datepicker widget when adding widget com.rey.material.widget.DatePicker in xml not compiling

java.lang.NullPointerException
	at android.graphics.Canvas.drawText(Canvas.java:1665)
	at com.rey.material.widget.DatePicker$MonthView.onDraw(DatePicker.java:563)
	at android.view.View.draw(View.java:15231)
	at android.view.View.draw(View.java:15140)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3405)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
	at android.widget.ListView.drawChild(ListView.java:3396)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
	at android.widget.AbsListView.dispatchDraw(AbsListView.java:2603)
	at android.widget.ListView.dispatchDraw(ListView.java:3391)
	at android.support.v7.internal.widget.ListViewCompat.dispatchDraw(ListViewCompat.java:102)
	at android.view.View.draw(View.java:15234)
	at android.widget.AbsListView.draw(AbsListView.java:4110)
	at android.view.View.draw(View.java:15140)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3405)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
	at android.view.View.draw(View.java:15138)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3405)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
	at android.view.View.draw(View.java:15138)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3405)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
	at android.view.View.draw(View.java:15234)
	at android.view.View.draw(View.java:15140)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3405)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
	at android.view.View.draw(View.java:15234)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:601)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:323)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:350)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:497)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:485)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:894)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:485)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:590)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.doRender(AndroidLayoutPreviewToolWindowManager.java:644)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.access$1700(AndroidLayoutPreviewToolWindowManager.java:79)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7$1.run(AndroidLayoutPreviewToolWindowManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7.run(AndroidLayoutPreviewToolWindowManager.java:581)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by rey5137** [comment]
Seam like you didn't call `setDateRange()` and `setDate()` to set the range of selectable date and current selected date.
