### ISSUE TITLE
NullPointer while Trying to use the progress indicator

### ISSUE THREAD

**Issue by inteist** [rey5137/material#17]
Copying the code from the sample app 

```java
    <com.rey.material.widget.ProgressView
        android:id="@+id/progress_wheel"
        android:layout_width="32dp"
        android:layout_height="32dp"
        app:pv_autostart = "true"
        app:pv_circular="true"
        app:pv_progressStyle="@style/CircularProgressDrawableStyle"
        app:pv_progressMode="indeterminate"/>
```
I tried to wrap it in a FrameLayout (just in case) like it is done in the sample app to no avail. Any idea what's going on?

and still getting this:

```java
04-02 18:33:48.550    1670-1670/info.androidz.horoscope E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at com.rey.material.widget.ProgressView.getProgressMode(ProgressView.java:110)
            at com.rey.material.widget.ProgressView.onAttachedToWindow(ProgressView.java:96)
            at android.view.View.dispatchAttachedToWindow(View.java:11755)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2424)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2424)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2424)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2424)
            at android.view.ViewGroup.addViewInner(ViewGroup.java:3417)
            at android.view.ViewGroup.addViewInLayout(ViewGroup.java:3354)
            at android.view.ViewGroup.addViewInLayout(ViewGroup.java:3335)
            at android.support.v4.view.ViewPager.addView(ViewPager.java:1307)
            at android.view.ViewGroup.addView(ViewGroup.java:3194)
            at android.view.ViewGroup.addView(ViewGroup.java:3170)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:968)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1136)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1499)
            at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:488)
            at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:163)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:1073)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:919)
            at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1441)
            at android.view.View.measure(View.java:15172)
```

**Comment by rey5137** [comment]
Can you pls show me the CircularProgressDrawableStyle you used?

**Comment by inteist** [comment]
I just imported the library and copied this from your sample app.

Isn't it included in the library?

**Comment by inteist** [comment]
It looks like it is not... WHY?!? :)

**Comment by rey5137** [comment]
`CircularProgressDrawableStyle` is the style defined in demo app. The lib has `Material.Drawable.CircularProgress` style for circular progress drawable.

**Comment by inteist** [comment]
I see now. This is quite confusing IMO...

So how circular progress should be used then?

**Comment by inteist** [comment]
I tried removing the style completely hoping to get the default style but it still crashes.

**Comment by rey5137** [comment]
You can set `app:pv_progressStyle="@style/Material.Drawable.CircularProgress"` for default style. 
In next version, I will fix progress view constructor to pass a default style in case you don't set it.

**Comment by inteist** [comment]
Maybe it's too late or something but I already tried that after your previous comment and it did not work.

Here's the code I have
```xml
    <com.rey.material.widget.ProgressView
        android:id="@+id/progress_wheel"
        android:layout_width="@dimen/sign_width"
        android:layout_height="@dimen/sign_height"
        app:pv_autostart="true"
        app:pv_circular="true"
        app:cpd_strokeColor="@color/light_primary_color"
        app:pv_progressStyle="@style/Material.Drawable.CircularProgress"
        app:pv_progressMode="indeterminate"/>

```

**Comment by rey5137** [comment]
In ProgressView constructor codes has that check `progressStyleId > 0` (the correct should be `progressStyleId != 0`). Maybe that cause the CircularProgressDrawable isn't created in your case. I will fixed it in next version.

**Comment by inteist** [comment]
Sounds good. I think you should use the default styles in the demo app which also serves kind of a test app as fas as I understand. Right now, you are not using the defaults and missing some issues such as in this case.

**Comment by rey5137** [comment]
I have released new 1.1.0 version. Please check it.

**Comment by inteist** [comment]
Hey Rey, 

I have 
```
compile 'com.github.rey5137:material:1.+'
```

but when I sync up the project it does not pull the update lib for some reason. Did you publish it to jcenter/maven?

**Comment by inteist** [comment]
UPD: I manually set it up to 1.1.0 and then it did sync up. Weird... Any idea why that did not pick up the change with the 1.+ ?

**Comment by inteist** [comment]
The spinner does not show up now... at all...
I tried removing the style completely too (in case it interferes somehow) but it did not help.
