### ISSUE TITLE
Dialog - Activity leak when orientation Change 

### ISSUE THREAD

**Issue by candeiasdan** [rey5137/material#170]
When orientation changes Activity leaks:

    15:02:04.041  10808-10808/com.scrive.pose_sign E/WindowManager﹕ android.view.WindowLeaked: Activity com.scrive.pose_sign.MainActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{42102238 G.E..... R.....ID 0,0-896,540} that was originally added here
                at android.view.ViewRootImpl.<init>(ViewRootImpl.java:393)
                at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
                at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
                at android.app.Dialog.show(Dialog.java:291)
                at com.rey.material.app.Dialog.show(Dialog.java:916)
                at android.app.Dialog.onRestoreInstanceState(Dialog.java:443)
                at android.support.v4.app.DialogFragment.onActivityCreated(DialogFragment.java:388)
                at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1794)
                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:977)
                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1136)
                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1118)
                at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1927)
                at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:544)
                at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1239)
                at android.app.Activity.performStart(Activity.java:5322)
                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2569)
                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2653)
                at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4351)
                at android.app.ActivityThread.access$900(ActivityThread.java:156)
                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1361)
                at android.os.Handler.dispatchMessage(Handler.java:102)
                at android.os.Looper.loop(Looper.java:157)
                at android.app.ActivityThread.main(ActivityThread.java:5872)
                at java.lang.reflect.Method.invokeNative(Native Method)
                at java.lang.reflect.Method.invoke(Method.java:515)
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
                at dalvik.system.NativeStart.main(Native Method)

How am i using this Dialog (inside Activity):

    SimpleDialog.Builder builder = new SimpleDialog.Builder() {};
    builder.multiChoiceItems(new String[]{"a","b"})
                    .title("title here")
                    .positiveAction(getResources().getString(android.R.string.ok))
                    .negativeAction(getResources().getString(android.R.string.cancel));

    DialogFragment fragment = DialogFragment.newInstance(builder);
    fragment.show(getSupportFragmentManager(), "tag_dialog");

**Comment by rey5137** [comment]
I have released a new version that fixed this bug.
