### ISSUE TITLE
android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by codezjx** [rey5137/material#177]
android.content.res.Resources$NotFoundException: Resource is not a ColorStateList (color or path): TypedValue{t=0x2/d=0x7f0101bd a=6}
            at android.content.res.Resources.loadColorStateList(Resources.java:2337)
            at android.content.res.TypedArray.getColorStateList(TypedArray.java:343)
            at com.rey.material.app.Dialog.applyStyle(Dialog.java:207)
            at com.rey.material.app.DatePickerDialog.applyStyle(DatePickerDialog.java:74)
            at com.rey.material.app.Dialog.init(Dialog.java:160)

Show this crash error if my app don't use "Theme.AppCompat.Light.DarkActionBar", when I change to this, everything works fine. Why?

**Comment by laszlo-galosi** [comment]
Yes I have the same issue, and my Base.Theme is "Theme.AppCompat.Light.NoActionBar" and it's required to be that, because I use Material Design library Toolbar. Is there any way to fix this?

**Comment by laszlo-galosi** [comment]
My stacjtrace us:
 android.content.res.Resources$NotFoundException: Resource is not a ColorStateList (color or path): TypedValue{t=0x2/d=0x7f010204 a=3}
            at android.content.res.Resources.loadColorStateList(Resources.java:2068)
            at android.content.res.TypedArray.getColorStateList(TypedArray.java:342)
            at com.rey.material.app.Dialog.applyStyle(Dialog.java:251)
            at com.rey.material.app.DatePickerDialog.applyStyle(DatePickerDialog.java:74)
            at com.rey.material.app.Dialog.init(Dialog.java:176)
            at com.rey.material.app.Dialog.<init>(Dialog.java:120)
            at com.rey.material.app.DatePickerDialog.<init>(DatePickerDialog.java:63)
            at com.rey.material.app.DatePickerDialog$Builder.onBuild(DatePickerDialog.java:814)
            at com.rey.material.app.Dialog$Builder.build(Dialog.java:1498)

**Comment by laszlo-galosi** [comment]
Looks like, it's casued by the default di_actionTextColor style property which in default refers to the theme, ?attr/colorControlActivated and it requires a colorStateList, and I only used a simple color in my theme.
And iz looks like, there are problems with attributes, which uses theheme specific attribute refrences for ex: dp_headerPrimaryColor, dp_selectionColor uses ?attr/colorPrimary.
So I define a custom style, and overwrite these problematic attributes with direct color references.
