### ISSUE TITLE
Rendering Problems in xml - unable to view the layout in xml

### ISSUE THREAD

**Issue by sateeshv** [rey5137/material#217]
More Information:

Using Android Studio 1.3
Version 1.0.0 

XML - when trying to view the preview unable to preview and the message displays is 

Rendering Problems 
java.lang.NullPointerException
	at com.rey.material.app.ThemeManager.registerOnThemeChangedListener(ThemeManager.java:181)
	at com.rey.material.widget.Button.onAttachedToWindow(Button.java:73)
	at android.view.View.dispatchAttachedToWindow(View.java:13525)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
	at android.view.AttachInfo_Accessor.setAttachInfo(AttachInfo_Accessor.java:42)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:422)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:321)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:350)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:511)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:499)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:888)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:499)
	at com.android.tools.idea.rendering.RenderTask.access$600(RenderTask.java:72)
	at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:611)
	at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:608)
	at com.android.tools.idea.rendering.RenderService.runRenderAction(RenderService.java:363)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:608)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:630)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.doRender(AndroidLayoutPreviewToolWindowManager.java:643)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.access$1700(AndroidLayoutPreviewToolWindowManager.java:80)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7$1.run(AndroidLayoutPreviewToolWindowManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7.run(AndroidLayoutPreviewToolWindowManager.java:580)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)

**Comment by sateeshv** [comment]
Can you please let me know what went wrong.

**Comment by umesh0492** [comment]
ThemeManager.init(this, 1, 0, null);  see #208

**Comment by lvl4fi4** [comment]
i got same rendering problem too! 
this line : ThemeManager.init(this, 1, 0, null); just solved the start up crash, not the rendering problem!

**Comment by lvl4fi4** [comment]
i just fixed the rendering problem by adding some   if(!isInEditMode()) :P 

see the error was on : ` ThemeManager.getInstance().registerOnThemeChangedListener(this);`

wich i just changed the : 

`   @Override
    protected void onAttachedToWindow() {
        super.onAttachedToWindow();
        if(mStyleId != 0) {
            ThemeManager.getInstance().registerOnThemeChangedListener(this);
            onThemeChanged(null);
        }
    } 
`
To this: 
 
    @Override
    protected void onAttachedToWindow() {
        super.onAttachedToWindow();
        if(mStyleId != 0) {
            if(!isInEditMode()){
            ThemeManager.getInstance().registerOnThemeChangedListener(this);
            onThemeChanged(null);}
        }
    }

**Comment by brunano21** [comment]
@lvl4fi4 
I'll try this once I got home. However this is the smallest of all problems :imho:

**Comment by lvl4fi4** [comment]
@brunano21 yep! i just needed the `Ctrl+Shift+R` to fix the whole thing! :+1:

**Comment by brunano21** [comment]
@lvl4fi4 which file did you modified?

**Comment by lvl4fi4** [comment]
each class in library used above code. most of them in widget folder . like buttin edittext swich etc... sorry for bad typing im on phone

**Comment by lvl4fi4** [comment]
use find replace wud b easy

**Comment by brunano21** [comment]
Hold on, but I'm using the version coming from gradle.

**Comment by lvl4fi4** [comment]
you gotta use the demo app library . no difference. i did use gradle too but that sucks so i decided to see whats going on library source

**Comment by brunano21** [comment]
Yeah, but I cannot use the demo app into my own app...damn!

**Comment by brunano21** [comment]
Maybe it's time @rey5137 fixes that issue..among the others.

**Comment by lvl4fi4** [comment]
yes @rey5137 ,
what u need is importing modul to ur project and make it compile in grade . just select the library folder in demo app .

**Comment by ananth10** [comment]
But I could not edit that class file.

**Comment by rey5137** [comment]
I have released 1.2.2 version. Pls check and see if it's fixed.

**Comment by ananth10** [comment]
Thank you rey. i will check it and update you.

**Comment by ananth10** [comment]
Yess. You have done . issue fixed :)
