### ISSUE TITLE
com.android.support:appcompat-v7:23+ not have Spinner_android_gravity

### ISSUE THREAD

**Issue by grestuccia1** [rey5137/material#222]
java.lang.RuntimeException: Unable to start activity ComponentInfo{yobdo.yobapp/yobdo.yobapp.activity.EditPositionActivity}: android.view.InflateException: Binary XML file line #69: Error inflating class com.rey.material.widget.Spinner
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: android.view.InflateException: Binary XML file line #69: Error inflating class com.rey.material.widget.Spinner
            at android.view.LayoutInflater.createView(LayoutInflater.java:633)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:257)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)

**Comment by ppamorim** [comment]
+1 Same here!

**Comment by ppamorim** [comment]
@rey5137 Impossible to use with SDK 23 :(

**Comment by golontico** [comment]
Same error

**Comment by aumidbek** [comment]
same error

**Comment by Possimpible** [comment]
Turns out all `_android_gravity` `_prompt` and `_disableChildrenWhenDisabled` were straight up all removed in 23. http://developer.android.com/sdk/support_api_diff/23/changes/android.support.v7.appcompat.R.styleable.html

**Comment by rey5137** [comment]
I have published 1.2.1.6-SNAPSHOT version that fixed this issue. Pls test it out.

**Comment by Possimpible** [comment]
Snapshot version works okay for me. Thanks a lot.

**Comment by ppamorim** [comment]
@rey5137 1.2.2-SNAPSHOT don't have fixed it yet?

**Comment by rey5137** [comment]
@ppamorim Yes, pls use 1.2.1.6-SNAPSHOT.

**Comment by golontico** [comment]
@rey5137  if i use
 compile 'com.github.rey5137:material:1.2.1.6-SNAPSHOT'
Return this error
Error:(27, 13) Failed to resolve: com.github.rey5137:material:1.2.1.6-SNAPSHOT
<a href="openFile">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

With
compileSdkVersion 23
buildToolsVersion '22.0.1'
targetSdkVersion 22

**Comment by rey5137** [comment]
Did you add the snapshot repository?

```gradle
repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```

**Comment by golontico** [comment]
nop

**Comment by tasomaniac** [comment]
I am getting exact same issue with the old library ViewPagerIndicator from JakeWharton. It is related to LinePageIndicator. Is it related to the removed attributes in the support library?

```
Warning can't find referenced method 'float ceil(float)' in library class android.util.FloatMath
```

**Comment by aumidbek** [comment]
Snapshot version works okay. Thanks a lot.

**Comment by ppamorim** [comment]
@rey5137 ProgressView don't exists on 1.2.1.6 :( I can't use this version. Do you know any date to release a stable version with this issue fixed?

**Comment by Possimpible** [comment]
@ppamorim Are you sure? I use ProgressView in my app with 1.2.1.6-SNAPSHOT just fine.

**Comment by golontico** [comment]
Hey people some one can help me to know how to set the snapshot..... i dont know how to

**Comment by adityanaik** [comment]
Open build.gradle (Module: app)

Change `compile 'com.github.rey5137:material:1.2.1'`
to `compile 'com.github.rey5137:material:1.2.1.6-SNAPSHOT'`

Then after `apply plugin: 'com.android.application'` , put
`repositories {
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}`

Then make a Gradle sync as suggested by Android Studio.

**Comment by golontico** [comment]
@adityanaik thanks!

**Comment by 4nd3250n** [comment]
Where can one find this "snapshot"?

**Comment by 4nd3250n** [comment]
Is this snapshot available for download?
if not, what must be changed in source code?

**Comment by sud007** [comment]
building with 1.2.16 doesn't work for me either.

back to  'com.github.rey5137:material:1.2.2'
