### ISSUE TITLE
endering Problems java.lang.NullPointerException   at com.rey.material.app.ThemeManager.registerOnThemeChangedListener

### ISSUE THREAD

**Issue by humazed** [rey5137/material#229]
When I try to see the demo app that you provided, I see that error when I try to open any layout.
I didn't change anything in your code. and I try to rebuild but nothing work.

java.lang.NullPointerException
	at com.rey.material.app.ThemeManager.registerOnThemeChangedListener(ThemeManager.java:181)
	at com.rey.material.widget.TextView.onAttachedToWindow(TextView.java:78)
	at android.view.View.dispatchAttachedToWindow(View.java:14514)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2843)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2843)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2843)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2843)
	at android.view.AttachInfo_Accessor.setAttachInfo(AttachInfo_Accessor.java:42)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:232)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:426)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:350)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:511)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:499)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:888)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:499)
	at com.android.tools.idea.rendering.RenderTask.access$600(RenderTask.java:72)
	at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:611)
	at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:608)
	at com.android.tools.idea.rendering.RenderService.runRenderAction(RenderService.java:365)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:608)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:630)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.doRender(AndroidLayoutPreviewToolWindowManager.java:643)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.access$1700(AndroidLayoutPreviewToolWindowManager.java:80)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7$1.run(AndroidLayoutPreviewToolWindowManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7.run(AndroidLayoutPreviewToolWindowManager.java:580)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by asep-ridwan** [comment]
i have same case

**Comment by brunano21** [comment]
same problem for me. I solved with (on your activity)
    protected void onCreate(Bundle savedInstanceState) {
        ThemeManager.init(this, 1, 0, null);
     
But I do not think this is a solution.

**Comment by reshma30** [comment]
@brunano21  thanx that solved my problem. Agree to you on this.

**Comment by saeed-zh** [comment]
@brunano21 
is that you mean I must put this command in every Activity class?
I put this in one of my class that extends from "Application". till two days ago everything is fine but now i got this error. I didn't change anything too.
