### ISSUE TITLE
 java.lang.IllegalArgumentException thrown when using EditText in FragmentViewPager

### ISSUE THREAD

**Issue by michel-t-86** [rey5137/material#230]
I have a layout with only one EditText element:

    <ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true"
        android:isScrollContainer="true"
        android:paddingBottom="@dimen/activity_vertical_margin"
        android:paddingLeft="32dp"
        android:paddingRight="16dp">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:paddingTop="72dp">

        <com.rey.material.widget.EditText
            android:id="@+id/name"
            style="@style/Material.Widget.EditText.Light"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginBottom="@dimen/field_top_padding"
            android:hint="@string/name"
            android:inputType="number"
            app:et_dividerPadding="16dp" />

    </LinearLayout>
    </ScrollView>

It is used in Fragment:

    package au.com.broscience.caloriecalculator.userprofile;
    import android.os.Bundle;
    import android.support.v4.app.Fragment;
    import android.view.LayoutInflater;
    import android.view.View;
    import android.view.ViewGroup;

    import au.com.broscience.caloriecalculator.R;

    /**
     * A simple {@link Fragment} subclass.
     */
    public class BlankFragment1 extends Fragment {

        public BlankFragment1() {
            // Required empty public constructor
        }

        @Override
        public View onCreateView(LayoutInflater inflater, ViewGroup container,
                                 Bundle savedInstanceState) {
            // Inflate the layout for this fragment
            return inflater.inflate(R.layout.fragment_user_details, container, false);
        }
    }

The fragment is used in a ViewPager so that the user can swipe through between different fragments.

When that particular fragment is used, the error below occurs? It only occurs once the user swipe past it and then comes back to it.
    java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.widget.TextView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/wqrgdfbvxcbvx. Make sure other views do not use the same id.
            at android.view.View.onRestoreInstanceState(View.java:12308)
            at android.view.View.dispatchRestoreInstanceState(View.java:12284)
            at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2617)
            at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2623)
            at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2623)
            at android.view.View.restoreHierarchyState(View.java:12262)
            at android.support.v4.app.Fragment.restoreViewState(Fragment.java:468)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1043)
            at android.support.v4.app.FragmentManagerImpl.attachFragment(FragmentManager.java:1375)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:728)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1562)
            at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:535)
            at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
            at android.support.v4.view.ViewPager$3.run(ViewPager.java:251)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
            at android.view.Choreographer.doCallbacks(Choreographer.java:562)
            at android.view.Choreographer.doFrame(Choreographer.java:531)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
            at android.os.Handler.handleCallback(Handler.java:730)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by michel-t-86** [comment]
i was missing the app:et_inputId tag in my EditText

    <com.rey.material.widget.EditText
        android:id="@+id/name"
        style="@style/Material.Widget.EditText.Light"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginBottom="@dimen/field_top_padding"
        android:hint="@string/name"
        android:inputType="number"
        app:et_inputId="@+id/name_input"
        app:et_dividerPadding="16dp" />
