### ISSUE TITLE
Dialog crash 2

### ISSUE THREAD

**Issue by omidjoon** [rey5137/material#247]
9-11 07:41:57.830    8253-8253/ir.Reserve.reservation E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: ir.Reserve.reservation, PID: 8253
    java.lang.RuntimeException: Failed to resolve attribute at index 15
            at android.content.res.TypedArray.getColorStateList(TypedArray.java:425)
            at com.rey.material.app.Dialog.applyStyle(Dialog.java:251)
            at com.rey.material.app.SimpleDialog.applyStyle(SimpleDialog.java:84)
            at com.rey.material.app.Dialog.init(Dialog.java:176)
            at com.rey.material.app.Dialog.<init>(Dialog.java:120)
            at com.rey.material.app.SimpleDialog.<init>(SimpleDialog.java:72)
            at ir.Reserve.reservation.Doctors.Doctor_TimerAndSickness$2.onClick(Doctor_TimerAndSickness.java:216)
            at android.view.View.performClick(View.java:4756)
            at android.view.View$PerformClick.run(View.java:19749)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by omidjoon** [comment]
and this is my code
SimpleDialog builder = new SimpleDialog(Doctor_TimerAndSickness.this,R.style.SimpleDialog) ;
                    builder.title("hooy");
                    builder.positiveAction("ha");

					builder.show();


whats the problem my friend?

**Comment by rey5137** [comment]
Can you post your SimpleDialog style ?

**Comment by omidjoon** [comment]
hi
this problem solved .
thanks .
