### ISSUE TITLE
Button - Rendering problem.

### ISSUE THREAD

**Issue by brunano21** [rey5137/material#248]
I'm using Android Studio and with the following button xml into the main_activity.xml I get the below error:
    <com.rey.material.widget.Button
        android:id="@+id/my_btn"
        android:layout_width="match_parent"
        android:layout_height="@dimen/bt_height"
        android:layout_marginRight="36sp"
        android:layout_marginLeft="36sp"
        android:layout_weight="0.4"
        android:layout_marginTop="16sp"
        android:text="TEXT"
        android:textSize="@dimen/t2"
        android:background="@color/colorPrimary"
        app:rd_enable="true"
        app:v_styleId="@array/button_flat"
        />
However, if I run the app into my Nexus 5 (4.4.2) I see the button, but not with the style I have chosen. 

`Rendering Problems Missing styles. Is the correct theme chosen for this layout?  Use the Theme combo box above the layout to choose a different layout, or fix the theme style references.  Failed to find style with id 0x2030009 in current theme` .

Seems the problems is related to `app:v_styleId="@array/button_flat"`. Any suggestion?? 
Thanks

**Comment by lvl4fi4** [comment]
i got same problem with below error:


java.lang.NullPointerException
	at com.rey.material.app.ThemeManager.registerOnThemeChangedListener(ThemeManager.java:181)
	at com.rey.material.widget.TextView.onAttachedToWindow(TextView.java:78)
	at android.view.View.dispatchAttachedToWindow(View.java:13406)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2714)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2714)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2714)
	at android.view.AttachInfo_Accessor.setAttachInfo(AttachInfo_Accessor.java:42)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:408)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:332)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:350)
	at com.android.tools.idea.rendering.RenderService$5.compute(RenderService.java:688)
	at com.android.tools.idea.rendering.RenderService$5.compute(RenderService.java:677)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:932)
	at com.android.tools.idea.rendering.RenderService.createRenderSession(RenderService.java:677)
	at com.android.tools.idea.rendering.RenderService.render(RenderService.java:815)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.doRender(AndroidLayoutPreviewToolWindowManager.java:646)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.access$1700(AndroidLayoutPreviewToolWindowManager.java:82)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7$1.run(AndroidLayoutPreviewToolWindowManager.java:589)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
	at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7.run(AndroidLayoutPreviewToolWindowManager.java:584)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:327)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by saeed-zh** [comment]
I did not have this problem in first use of this library, recently when I open my layouts, it couldn't render layout and show problem above. i have no change on my code. 
do you have find any solution?
