### ISSUE TITLE
Crash app when use Spinner OnItemClick when add spn_labelEnable="false" 

### ISSUE THREAD

**Issue by michaellct** [rey5137/material#274]
if don't add app:spn_labelEnable ,everthing is ok

 <com.rey.material.widget.Spinner
            android:id="@+id/spinner_label"
            style="@style/LightSpinner"
            android:layout_width="wrap_content"
            android:layout_height="48dp"
            android:minWidth="128dp"
            app:spn_labelEnable="false"
             />

    java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
            at android.view.ViewGroup.addViewInner(ViewGroup.java:3593)
            at android.view.ViewGroup.addView(ViewGroup.java:3446)
            at android.view.ViewGroup.addView(ViewGroup.java:3391)
            at android.view.ViewGroup.addView(ViewGroup.java:3367)
            at com.rey.material.widget.Spinner.onDataInvalidated(Spinner.java:927)
            at com.rey.material.widget.Spinner.setSelection(Spinner.java:422)
            at com.rey.material.widget.Spinner.performItemClick(Spinner.java:898)
            at com.rey.material.widget.Spinner$DropdownPopup$3.onItemClick(Spinner.java:1271)
            at com.rey.material.widget.Spinner$DropDownAdapter.onClick(Spinner.java:1140)
            at com.rey.material.widget.RippleManager.run(RippleManager.java:100)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5117)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by rey5137** [comment]
Can you please try 1.2.2 version and see if it's fixed?

**Comment by krisha23** [comment]
I had exactly the same issue, I tried 1.2.2 and it did not work for me!
