### ISSUE TITLE
BottomSheetDialog crash java.lang.NullPointerException

### ISSUE THREAD

**Issue by fortuna58rus** [rey5137/material#285]
java.lang.NullPointerException
	at com.rey.material.app.BottomSheetDialog$ContainerFrameLayout.dispatchTouchEvent(BottomSheetDialog.java:473)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1978)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1978)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
	at android.view.ViewGroup.cancelAndClearTouchTargets(ViewGroup.java:2068)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2573)
	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:2739)
	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:4201)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3045)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4949)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1043)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
	at dalvik.system.NativeStart.main(Native Method)

version 1.2.1

**Comment by alirezaaa** [comment]
I'm getting that exception too!

**Comment by andrewpros** [comment]
Any input on this?

**Comment by rey5137** [comment]
I have released 1.2.2 version that fixed this bug.

**Comment by luohong** [comment]
I'm getting that exception too! many times
