### ISSUE TITLE
ContactEditText not Working on Dialog

### ISSUE THREAD

**Issue by parsidev** [rey5137/material#289]
Hello,

I create a ContactEditText Programmatically in a Dialog with this code
```java
final ContactEditText contactEditText = new ContactEditText(context);
        contactEditText.applyStyle(R.style.MyContactEditText);
        contactEditText.setHint(item);
        RelativeLayout.LayoutParams params = new RelativeLayout.LayoutParams(RelativeLayout.LayoutParams.MATCH_PARENT, RelativeLayout.LayoutParams.WRAP_CONTENT);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
            params.addRule(RelativeLayout.ALIGN_PARENT_END);
        }
        params.addRule(RelativeLayout.ALIGN_PARENT_RIGHT);
        params.addRule(RelativeLayout.ALIGN_PARENT_TOP);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
            params.setMarginStart(5);
        }
        params.setMargins(5, 0, 0, 0);
        float density = context.getResources().getDisplayMetrics().density;
        int paddingDp = (int) (50 * density);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
            contactEditText.setPaddingRelative(paddingDp, 0, 0, 0);
        }
        contactEditText.setPadding(paddingDp, 0, 0, 0);
        contactEditText.setLayoutParams(params);
        contactEditText.setId(R.id.ServiceDialogContactEditText);
        contactEditText.setTypeface(TypeFace.fontParsiDevLight(context));
        linearLayout.addView(contactEditText);
```
MyContactEditText:
```xml
<style name="ContactEditText" parent="Material.Widget.EditText.Light">
        <item name="cet_spanHeight">32dp</item>
        <item name="cet_spanMaxWidth">150dp</item>
        <item name="cet_spanPaddingLeft">8dp</item>
        <item name="cet_spanPaddingRight">12dp</item>
        <item name="cet_spanTextSize">14sp</item>
        <item name="cet_spanTextColor">@color/primary_text_material_light</item>
        <item name="cet_spanBackgroundColor">#FFE0E0E0</item>
        <item name="cet_spanSpacing">4dp</item>
    </style>

    <style name="MyContactEditText" parent="ContactEditText">
        <item name="android:completionThreshold">2</item>
        <item name="android:dropDownSelector">@drawable/list_selector_background_holo_light</item>
        <item name="android:imeOptions">actionNext|flagNoEnterAction|flagNoExtractUi</item>
        <item name="android:inputType">textEmailSubject|textMultiLine</item>
        <item name="et_autoCompleteMode">multi</item>
        <item name="et_dividerPadding">4dp</item>
        <item name="et_inputId">@id/ServiceDialogTextFieldEtContactInput</item>
        <item name="et_supportMode">none</item>
    </style>
```

but when running, my app is force close and send this error
```
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime: FATAL EXCEPTION: main
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime: java.lang.ClassCastException: com.rey.material.widget.EditText$InternalEditText cannot be cast to com.rey.material.widget.EditText$InternalMultiAutoCompleteTextView
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at com.rey.material.widget.EditText.onSelectionChanged(EditText.java:2396)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at com.rey.material.widget.EditText$InternalMultiAutoCompleteTextView.onSelectionChanged(EditText.java:3806)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at android.widget.TextView.spanChange(TextView.java:7922)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at android.widget.TextView$ChangeWatcher.onSpanAdded(TextView.java:8259)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at android.text.SpannableStringBuilder.sendSpanAdded(SpannableStringBuilder.java:909)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:614)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:520)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at android.text.Selection.setSelection(Selection.java:95)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at android.text.Selection.setSelection(Selection.java:104)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at android.text.method.ArrowKeyMovementMethod.initialize(ArrowKeyMovementMethod.java:304)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at android.widget.TextView.setText(TextView.java:3316)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at android.widget.TextView.setText(TextView.java:3184)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at android.widget.EditText.setText(EditText.java:78)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at android.widget.TextView.<init>(TextView.java:1108)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at android.widget.EditText.<init>(EditText.java:58)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at android.widget.AutoCompleteTextView.<init>(AutoCompleteTextView.java:137)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at android.widget.MultiAutoCompleteTextView.<init>(MultiAutoCompleteTextView.java:70)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at com.rey.material.widget.EditText$InternalMultiAutoCompleteTextView.<init>(EditText.java:3745)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at com.rey.material.widget.EditText.applyStyle(EditText.java:160)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at com.rey.material.widget.EditText.applyStyle(EditText.java:139)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at ir.parsidev.android.controls.ServiceDialogRequireItem.createContactEditText(ServiceDialogRequireItem.java:67)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at ir.parsidev.android.controls.ServiceDialogRequireItem.setItems(ServiceDialogRequireItem.java:149)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at ir.parsidev.android.controls.ServiceDialogRequireItem.setUSSD(ServiceDialogRequireItem.java:42)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at ir.parsidev.android.controls.ServiceDialog.onClick(ServiceDialog.java:100)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at com.rey.material.widget.RippleManager.run(RippleManager.java:85)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:605)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:92)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4441)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
11-07 17:12:29.391 28093-28093/ir.parsidev.android.mastercharge E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

```

please help me solve this error.

**Comment by parsidev** [comment]
No one can help me?

**Comment by parsidev** [comment]
@rey5137 please help me, i need to solve this problem
