### ISSUE TITLE
java.lang.VerifyError: com/rey/material/app/SimpleDialog

### ISSUE THREAD

**Issue by ckalpit** [rey5137/material#305]
I am getting this error only on specific devices. it occurs when simple dialog box is created, 
here is whole stack trace

java.lang.VerifyError: com/rey/material/app/SimpleDialog
                                                                                 at com.rey.material.app.SimpleDialog$Builder.onBuild(SimpleDialog.java:660)
                                                                                 at com.rey.material.app.Dialog$Builder.build(Dialog.java:1496)
                                                                                 at com.rey.material.app.DialogFragment.onCreateDialog(DialogFragment.java:69)
                                                                                 at com.rey.material.app.DialogFragment.onCreateDialog(DialogFragment.java:12)
                                                                                 at android.support.v4.app.DialogFragment.getLayoutInflater(DialogFragment.java:308)
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
                                                                                 at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                                                 at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
                                                                                 at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
                                                                                 at android.os.Handler.handleCallback(Handler.java:733)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:136)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5052)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                                 at dalvik.system.NativeStart.main(Native Method)

**Comment by ckalpit** [comment]
Hi, sorry for reporting this, 

If any one else facing the same issue make sure you have updated version of the library,
I was using the library from so long and did not updated it but I have updated ('com.android.support:appcompat-v7:23.1.1') library in my project which was showing the above error on pre lollipop devices. 

so make sure you have both appcompat and this library updated . (or same as written in readme.md)
