### ISSUE TITLE
ArrayAdapter IndexOutOfBoundsException: Invalid index 0, size is 0

### ISSUE THREAD

**Issue by sinyakin** [rey5137/material#312]
sorry for my bad english)

i'm using your com.rey.material.widget.Spinner.
and for adding empty data in adapter throw exception.

java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
            at java.util.ArrayList.get(ArrayList.java:304)
            at com.bil24.adapter.VenueSpinnerAdapter.getView(VenueSpinnerAdapter.java:46)
            at com.rey.material.widget.Spinner.onDataInvalidated(Spinner.java:892)
            at com.rey.material.widget.Spinner.setSelection(Spinner.java:391)
            at com.rey.material.widget.Spinner.onDataChanged(Spinner.java:874)
            at com.rey.material.widget.Spinner.setAdapter(Spinner.java:428)
            at com.bil24.fragments.action.ActionFragment.onCreateView(ActionFragment.java:68)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
            at.....
![1](https://cloud.githubusercontent.com/assets/894006/11906296/6e167bd2-a5dc-11e5-81ab-2710d03ced09.png)
![2](https://cloud.githubusercontent.com/assets/894006/11906328/98ad7b2a-a5dc-11e5-92d9-e9965726d91c.png)

help me

**Comment by kdani41** [comment]
are you sure your list is not empty because it seems like at line 46 compiler is not able to get the item at the position it's looking for.

**Comment by sinyakin** [comment]
yes, my list is empty.
method getView called when list is empty and position = 0.

**Comment by kdani41** [comment]
In order for adapter to populate your list should be of some certain length. You can close this issue since this issue has nothing to do with the library.

**Comment by sinyakin** [comment]
standart spinner allow add empty list, but material spinner throws exception.

for example. first, i add list with n elements, after my list update and numbers of element = 0 and your lib throw exception. it is standart situation.

i changed your code from
```java
  private void onDataChanged() {
    if(this.mSelectedPosition == -1) {
      this.setSelection(0);
    } else if(this.mSelectedPosition < this.mAdapter.getCount()) {
      this.onDataInvalidated();
    } else {
      this.setSelection(this.mAdapter.getCount() - 1);
    }
  }
```
to:
```java
private void onDataChanged() {
    if (this.mSelectedPosition == -1) {
      this.setSelection(0);
    } else if (this.mSelectedPosition < this.mAdapter.getCount()) {
      this.onDataInvalidated();
    } 
   //todo my else
   else if (this.mSelectedPosition == this.mAdapter.getCount()) {
      this.removeAllViews();
    } else {
      this.setSelection(this.mAdapter.getCount() - 1);
    }
  }
```
and code from:
```java
  private void onDataInvalidated() {
    if(this.mAdapter != null) {
      int type;
      if(this.mLabelView == null) {
        this.removeAllViews();
      } else {
        for(type = this.getChildCount() - 1; type > 0; --type) {
          this.removeViewAt(type);
        }
      }
      type = this.mAdapter.getItemViewType(this.mSelectedPosition);
      View v = this.mAdapter.getView(this.mSelectedPosition, this.mRecycler.get(type), this);
      v.setFocusable(false);
      v.setClickable(false);
      if(v.getParent() != null) {
        ((ViewGroup)v.getParent()).removeView(v);
      }
      super.addView(v);
      this.mRecycler.put(type, v);
    }
  }
```
to:
```java
  private void onDataInvalidated() {
    if (this.mAdapter != null) {
      int type;
      if (this.mLabelView == null) {
        this.removeAllViews();
      } else {
        for (type = this.getChildCount() - 1; type > 0; --type) {
          this.removeViewAt(type);
        }
      }
      //todo my if
      if (mAdapter.getCount() != 0) {
        type = this.mAdapter.getItemViewType(this.mSelectedPosition);
        View v = this.mAdapter.getView(this.mSelectedPosition, this.mRecycler.get(type), this);
        v.setFocusable(false);
        v.setClickable(false);
        if (v.getParent() != null) {
          ((ViewGroup) v.getParent()).removeView(v);
        }
        super.addView(v);
        this.mRecycler.put(type, v);
      }
    }
  }
 ```
and it work fine.

may be my solution does not perfect.

i like your lib, but you could not fix the situation?

**Comment by dstd** [comment]
@sinyakin you can fork the library, fix the issue and send a pull request back
