### ISSUE TITLE
java.lang.NullPointerException in onDismiss

### ISSUE THREAD

**Issue by sinyakin** [rey5137/material#314]
after update your lib throw nullpointer in com.rey.material.app.DialogFragment.onDismiss.
builder = null.
i am creating dialog without builder.

java.lang.NullPointerException
            at com.rey.material.app.DialogFragment.onDismiss(DialogFragment.java:123)
            at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1259)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:175)
            at android.app.ActivityThread.main(ActivityThread.java:5279)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by azizbekian** [comment]
The same issue with 'com.github.rey5137:material:1.2.1.9-SNAPSHOT'
