### ISSUE TITLE
Spinner crash on Gingerbread 2.3

### ISSUE THREAD

**Issue by Arun-Kannan** [rey5137/material#337]
02-08 18:54:52.329 23706-23706/com.android.jaadu E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
                                                                        at android.content.res.TypedArray.getColor(TypedArray.java:326)
                                                                        at com.rey.material.util.ViewUtil.applyTextAppearance(Unknown Source)
                                                                        at com.rey.material.widget.TextView.setTextAppearance(Unknown Source)
                                                                        at com.rey.material.widget.Spinner.applyStyle(Unknown Source)
                                                                        at com.rey.material.widget.FrameLayout.applyStyle(Unknown Source)
                                                                        at com.rey.material.widget.FrameLayout.onThemeChanged(Unknown Source)
                                                                        at com.rey.material.widget.FrameLayout.onAttachedToWindow(Unknown Source)
                                                                        at android.view.View.dispatchAttachedToWindow(View.java:6156)
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:1122)
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:1127)
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:1127)
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:1127)
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:1127)
                                                                        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:1127)
                                                                        at android.view.ViewGroup.addViewInner(ViewGroup.java:2011)
                                                                        at android.view.ViewGroup.addViewInLayout(ViewGroup.java:1958)
                                                                        at android.widget.ListView.setupChild(ListView.java:1794)
                                                                        at android.widget.ListView.makeAndAddView(ListView.java:1748)
                                                                        at android.widget.ListView.fillDown(ListView.java:670)
                                                                        at android.widget.ListView.fillFromTop(ListView.java:727)
                                                                        at android.widget.ListView.layoutChildren(ListView.java:1598)
                                                                        at android.widget.AbsListView.onLayout(AbsListView.java:1323)
                                                                        at android.view.View.layout(View.java:7175)
                                                                        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:912)
                                                                        at android.view.View.layout(View.java:7175)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
                                                                        at android.view.View.layout(View.java:7175)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
                                                                        at android.view.View.layout(View.java:7175)
                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1254)
                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1130)
                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1047)
                                                                        at android.view.View.layout(View.java:7175)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
                                                                        at android.view.View.layout(View.java:7175)
                                                                        at android.support.v4.widget.DrawerLayout.onLayout(Unknown Source)
                                                                        at android.view.View.layout(View.java:7175)
                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1254)
                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1130)
                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1047)
                                                                        at android.view.View.layout(View.java:7175)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
                                                                        at android.view.View.layout(View.java:7175)
                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1254)
                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1130)
                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1047)
                                                                        at android.view.View.layout(View.java:7175)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
                                                                        at android.view.View.layout(View.java:7175)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
                                                                        at android.view.View.layout(View.java:7175)
                                                                        at android.view.ViewRoot.performTraversals(ViewRoot.java:1142)
                                                                        at android.view.ViewRoot.handleMessage(ViewRoot.java:1861)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                        at android.os.Looper.loop(Looper.java:130)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:3683)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:507)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:875)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:633)
                                                                        at dalvik.system.NativeStart.main(Native Method)

**Comment by Arun-Kannan** [comment]
Anyone found solution?
