### ISSUE TITLE
Dialog crash

### ISSUE THREAD

**Issue by SteveCampos** [rey5137/material#34]
When i try to create a Dialog.

```
import com.rey.material.app.Dialog;
Dialog dialog = new Dialog(context);
```

**The error is in this line**

```
Dialog dialog = new Dialog(context);
```

java.lang.RuntimeException: Unable to start activity android.content.res.Resources$NotFoundException: Resource is not a ColorStateList (color or path): TypedValue{t=0x2/d=0x7f0101af a=3}

```
     Caused by: android.content.res.Resources$NotFoundException: Resource is not a ColorStateList (color or path): TypedValue{t=0x2/d=0x7f0101af a=3}
            at android.content.res.Resources.loadColorStateList(Resources.java:2963)
            at android.content.res.TypedArray.getColorStateList(TypedArray.java:343)
            at com.rey.material.app.Dialog.applyStyle(Dialog.java:190)
            at com.rey.material.app.Dialog.init(Dialog.java:144)
            at com.rey.material.app.Dialog.<init>(Dialog.java:100)
            at com.rey.material.app.Dialog.<init>(Dialog.java:87)
            at com.rupture.jairsteve.rupture.wlan.onCreate(wlan.java:107)
```
**Does anyone know how to fix it? or is it a bug?**

**Comment by rey5137** [comment]
Which library version did you use? Can you please post your current theme style?

**Comment by SteveCampos** [comment]
Hi, thanks for respond
In dependeces
```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.github.rey5137:material:1.1.0'
    compile 'com.android.support:appcompat-v7:22.0.0'
    compile 'com.android.support:cardview-v7:22.0.0'
    compile 'com.android.support:support-v4:22.0.0'
}
```


My theme style

*Material.Light.NoActionBar.Fullscreen*

Now,  i get other error in same line cited up.
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rupture.jairsteve.rupture/com.rupture.jairsteve.rupture.wlan}: java.lang.RuntimeException: Failed to resolve attribute at index 12
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2314)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388)
            at android.app.ActivityThread.access$800(ActivityThread.java:148)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5312)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
     Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 12
            at android.content.res.TypedArray.getColorStateList(TypedArray.java:425)
            at com.rey.material.app.Dialog.applyStyle(Dialog.java:190)
            at com.rey.material.app.Dialog.init(Dialog.java:144)
            at com.rey.material.app.Dialog.<init>(Dialog.java:100)
            at com.rey.material.app.Dialog.<init>(Dialog.java:87)
            at com.rupture.jairsteve.rupture.wlan.onCreate(wlan.java:120)
            at android.app.Activity.performCreate(Activity.java:5953)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1128)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388)
            at android.app.ActivityThread.access$800(ActivityThread.java:148)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5312)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
```

**Comment by SteveCampos** [comment]
Solved the problem
**Change my theme in styles.xml**
```
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
    </style>
</resources>
```
**And set up this in manifest**
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="library.com.materialrey" >

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme" >
```
Dialog, and EditText work fine.! Your library is amazing, Thanks!
