### ISSUE TITLE
EditText Rendering Problems

### ISSUE THREAD

**Issue by SteveCampos** [rey5137/material#36]
I am trying to use EditText and i get error **Rendering Problems**

*Error*
Couldn't find theme resource ?attr/colorAccent for the current theme

```
java.lang.NumberFormatException: Color value '?attr/colorAccent' must start with #
	at com.android.layoutlib.bridge.impl.ResourceHelper.getColor(ResourceHelper.java:72)
	at android.content.res.BridgeTypedArray.getColorStateList(BridgeTypedArray.java:312)
	at com.rey.material.widget.EditText.applyStyle(EditText.java:154)
	at com.rey.material.widget.EditText.init(EditText.java:118)
	at com.rey.material.widget.EditText.<init>(EditText.java:100)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:379)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:99)
	at com.android.tools.idea.rendering.LayoutlibCallback.loadView(LayoutlibCallback.java:172)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:207)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:132)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:806)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:385)
```
**My layout_dialog_custom.xml**
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical">

    <com.rey.material.widget.EditText

        style="@style/Material.Widget.EditText.Light"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:textColor="@color/abc_primary_text_material_light"
        android:hint="Signal strength"
        android:text="Excellent"
        app:et_dividerHeight="0dp"
        android:textColorHint="@color/abc_secondary_text_material_light"
        app:et_supportMode="none"
        android:paddingTop="8dp"

    />
    <com.rey.material.widget.EditText
        style="@style/Material.Widget.EditText.Light"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:textColor="@color/abc_primary_text_material_light"
        android:hint="Signal strength"
        android:text="Excellent"
        app:et_dividerHeight="0dp"
        app:et_supportMode="none"
        android:paddingTop="8dp"
        />
   <com.rey.material.widget.EditText
        style="@style/Material.Widget.EditText.Light"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:textColor="@color/abc_primary_text_material_light"
        android:hint="Capabilities"
        android:text="WPA-PSK2"
        app:et_dividerHeight="0dp"
        app:et_supportMode="none"
        android:paddingTop="8dp"
        />
    <com.rey.material.widget.EditText
        style="@style/Material.Widget.EditText.Light"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:textColor="@color/abc_primary_text_material_light"
        android:text="WPA-PSK2"
        app:et_dividerHeight="0dp"
        app:et_supportMode="charCounter"
        android:paddingTop="8dp"
        android:textColorHint="@color/abc_secondary_text_material_light"
        android:hint="Password"
        android:inputType="textPassword"
        />
    <com.rey.material.widget.CheckBox
        style="@style/Material.Drawable.CheckBox"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Show password"
        android:textAppearance="@style/TextAppearance.AppCompat.Body1"
        android:textColor="@color/abc_primary_text_material_light"
        android:gravity="center_vertical"
        android:paddingLeft="24dp"
        android:layout_marginTop="8dp"
        android:checked="false"
        android:id="@+id/showPassword"
        />

</LinearLayout>
```
**Does anyone know how to fix it?**

**Comment by mehrad-rafigh** [comment]
Could you post your style.xml file(s)?

**Comment by SteveCampos** [comment]
**styles.xml**
```
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="android:Theme.Holo.NoActionBar.Fullscreen">
        <!-- Customize your theme here. -->
    </style>

    <style name="RaiseColorButtonRippleStyle" parent="Material.Drawable.Ripple.Touch.Light">
        <item name="android:background">@drawable/bg_bt_raise_color</item>
        <item name="rd_rippleColor">#33000000</item>
        <item name="rd_leftPadding">1dp</item>
        <item name="rd_topPadding">1dp</item>
        <item name="rd_rightPadding">1dp</item>
        <item name="rd_bottomPadding">2dp</item>
    </style>


    <style name="SimpleDialog" parent="Material.App.Dialog.Simple">
        <item name="di_inAnimation">@anim/anim_scale_in</item>
        <item name="di_outAnimation">@anim/anim_scale_out</item>
    </style>

</resources>
```

**Comment by rey5137** [comment]
Seem like you missing Material theme attribute. Here is example:
``` xml
     <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <!-- Customize your theme here. -->

        <!-- colorPrimary is used for the default action bar background -->
        <item name="colorPrimary">@color/colorPrimary</item>

        <!-- colorPrimaryDark is used for the status bar -->
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>

        <!-- colorAccent is used as the default value for colorControlActivated
             which is used to tint widgets -->
        <item name="colorAccent">@color/colorAccent</item>

        <!-- You can also set colorControlNormal, colorControlActivated
             colorControlHighlight & colorSwitchThumbNormal. -->
    </style>
```

**Comment by SteveCampos** [comment]
Thanks! Your library is awesome.
add missing Material theme attribute resolved problem.
**Now rendering works well.**

Sorry, i have another problem
**When i try to run i get Error inflating class**

```
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rupture.jairsteve.rupture/com.rupture.jairsteve.rupture.MainActivity}: android.view.InflateException: Binary XML file line #8: Error inflating class com.rey.material.widget.EditText
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2314)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388)
            at android.app.ActivityThread.access$800(ActivityThread.java:148)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5312)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
     Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.rey.material.widget.EditText
            at android.view.LayoutInflater.createView(LayoutInflater.java:633)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:377)
            at android.app.Activity.setContentView(Activity.java:2154)
            at com.rupture.jairsteve.rupture.MainActivity.onCreate(MainActivity.java:17)
            at android.app.Activity.performCreate(Activity.java:5953)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1128)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388)
            at android.app.ActivityThread.access$800(ActivityThread.java:148)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5312)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
            at android.view.LayoutInflater.createView(LayoutInflater.java:607)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:377)
            at android.app.Activity.setContentView(Activity.java:2154)
            at com.rupture.jairsteve.rupture.MainActivity.onCreate(MainActivity.java:17)
            at android.app.Activity.performCreate(Activity.java:5953)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1128)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388)
            at android.app.ActivityThread.access$800(ActivityThread.java:148)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5312)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
     Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 23
            at android.content.res.TypedArray.getColorStateList(TypedArray.java:425)
            at com.rey.material.widget.EditText.applyStyle(EditText.java:154)
            at com.rey.material.widget.EditText.init(EditText.java:118)
            at com.rey.material.widget.EditText.<init>(EditText.java:100)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
            at android.view.LayoutInflater.createView(LayoutInflater.java:607)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:377)
            at android.app.Activity.setContentView(Activity.java:2154)
            at com.rupture.jairsteve.rupture.MainActivity.onCreate(MainActivity.java:17)
            at android.app.Activity.performCreate(Activity.java:5953)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1128)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2267)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388)
            at android.app.ActivityThread.access$800(ActivityThread.java:148)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5312)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
```

To ensure that problems are not my code, create a simple class.
```
public class MainActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.layout_dialog_custom);
    }
```
**Error in this line**
```
setContentView(R.layout.layout_dialog_custom);
```

My layout_dialog_custom.xml is up.
Line #8,23
```
<com.rey.material.widget.EditText
```
