### ISSUE TITLE
Snackbar Style

### ISSUE THREAD

**Issue by Onwa1kenobi** [rey5137/material#385]
The snackbar used to work perfectly before till i updated the sdk. Now it crashes the app when I apply a style and the log says;

```
06-14 12:58:44.496 13180-13180/com.fifthtecnologies.muter E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.fifthtecnologies.muter, PID: 13180
                                                                            java.lang.RuntimeException: Unable to resume activity {com.fifthtecnologies.muter/com.fifthtecnologies.muter.MainActivity}: java.lang.RuntimeException: Failed to resolve attribute at index 21
                                                                                at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3231)
                                                                                at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3262)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2605)
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:177)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1469)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                at android.os.Looper.loop(Looper.java:194)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5622)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
                                                                             Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 21
                                                                                at android.content.res.TypedArray.getColorStateList(TypedArray.java:425)
                                                                                at com.rey.material.widget.SnackBar.applyStyle(SnackBar.java:255)
                                                                                at com.rey.material.widget.FrameLayout.applyStyle(FrameLayout.java:46)
                                                                                at com.fifthtecnologies.muter.MainActivity.onResume(MainActivity.java:286)
                                                                                at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1267)
                                                                                at android.app.Activity.performResume(Activity.java:6186)
                                                                                at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3216)
                                                                                at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3262) 
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2605) 
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:177) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1469) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                at android.os.Looper.loop(Looper.java:194) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5622) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754) 
06-14 12:58:45.147 13180-13277/com.fifthtecnologies.muter E/NativeCrypto: ssl=0x7f9f89f980 cert_verify_callback x509_store_ctx=0x7f91bff0b8 arg=0x0
06-14 12:58:45.147 13180-13277/com.fifthtecnologies.muter E/NativeCrypto: ssl=0x7f9f89f980 cert_verify_callback calling verifyCertificateChain authMethod=DHE_RSA
06-14 12:58:46.585 13180-13307/com.fifthtecnologies.muter E/NativeCrypto: ssl=0x7f9f89f980 cert_verify_callback x509_store_ctx=0x7f91bff0b8 arg=0x0
06-14 12:58:46.586 13180-13307/com.fifthtecnologies.muter E/NativeCrypto: ssl=0x7f9f89f980 cert_verify_callback calling verifyCertificateChain authMethod=DHE_RSA
```

This is how i use it.

```
Snackbar snackBar = new SnackBar(getApplicationContext());
        snackBar.applyStyle(R.style.Material_Widget_SnackBar_Mobile_MultiLine);
```

**Comment by Onwa1kenobi** [comment]
I fixed my problem by changing;
`Snackbar snackBar = new SnackBar(getApplicationContext());`
to
`Snackbar snackBar = new SnackBar(this);`
