### ISSUE TITLE
FloatingActionButton's setIcon method not working

### ISSUE THREAD

**Issue by zeshaoaaa** [rey5137/material#391]
# Description
I copy source code to my project from meterial-master, java code and xml files.
Because this copied button no icon, so I invoke setIcon method, error occur.

The error occurred when  'mSwitchIconAnimator.startAnimation(icon)' I found.

# Stacktrace

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setCallback(android.graphics.drawable.Drawable$Callback)' on a null object reference
                                                                    at com.rey.material.widget.FloatingActionButton$SwitchIconAnimator.startAnimation(FloatingActionButton.java:598)
                                                                    at com.rey.material.widget.FloatingActionButton.setIcon(FloatingActionButton.java:282)
                                                                    at postest.phonepos.Activity.main_menu.InventoryActivity.initLoatingBtn(InventoryActivity.java:150)

**Comment by zeshaoaaa** [comment]
Have someone can fit it? Thanks, my project need the animation.
