### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=16; index=20

### ISSUE THREAD

**Issue by shadowline** [rey5137/material#396]
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=16; index=20
	at android.widget.RelativeLayout$LayoutParams.addRule(RelativeLayout.java:1204)
	at com.rey.material.widget.SnackBar.applyStyle(SnackBar.java)
	                                    onThemeChanged(SnackBar.java)
	                                    text(SnackBar.java)
	                                    textSize(SnackBar.java)
	                                    ellipsize(SnackBar.java)
	                                    singleLine(SnackBar.java)
	                                    actionTextColor(SnackBar.java)
	                                    duration(SnackBar.java)
	                                    padding(SnackBar.java)
	                                    animationIn(SnackBar.java)
	                                    dismiss(SnackBar.java)
	                                    access$000(SnackBar.java)
	                                    access$200(SnackBar.java)
	at com.richinfo.drive.activity.MyRecordActivity.j(MyRecordActivity.java)
	at com.richinfo.drive.activity.MyRecordActivity.onCreate(MyRecordActivity.java)
	at android.app.Activity.performCreate(Activity.java:5206)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074)
	... 11 more

**Comment by shadowline** [comment]
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=16; index=20
     at android.widget.RelativeLayout$LayoutParams.addRule(RelativeLayout.java:1204)
     at com.rey.material.widget.SnackBar.show(SnackBar.java:842)
     at com.richinfo.drive.activity.MyRecordActivity.assignViews(MyRecordActivity.java:68)
     at com.richinfo.drive.activity.MyRecordActivity.onCreate(MyRecordActivity.java:45)
     at android.app.Activity.performCreate(Activity.java:5008)
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
     at android.app.ActivityThread.access$600(ActivityThread.java:130) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
     at android.os.Handler.dispatchMessage(Handler.java:99) 

hi, @rey5137  The bug happen on AndroidVersion:4.1.1,4.1.2. RelativeLayout.ALIGN_PARENT_START introduced with API level 17 ,I find this http://stackoverflow.com/questions/25763142/android-arrayindexoutofbounds-exception-on-addrule-in-layoutparams  ,please fix it

**Comment by hojatdelfan** [comment]
[thanks](http://www.goftare.com/)
