### ISSUE TITLE
The ListView shows null pointer exception

### ISSUE THREAD

**Issue by Yogesh0795** [rey5137/material#44]
The listview added in an xml file shows a null pointer exception.

java.lang.NullPointerException
	at android.support.v7.internal.widget.ListViewCompat.drawableStateChanged(ListViewCompat.java:91)
	at android.view.View.refreshDrawableState(View.java:16032)
	at android.view.View.dispatchAttachedToWindow(View.java:13546)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2688)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
	at android.view.AttachInfo_Accessor.setAttachInfo(AttachInfo_Accessor.java:42)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:422)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:321)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:350)
	at com.android.tools.idea.rendering.RenderService$5.compute(RenderService.java:708)
	at com.android.tools.idea.rendering.RenderService$5.compute(RenderService.java:697)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:932)
	at com.android.tools.idea.rendering.RenderService.createRenderSession(RenderService.java:697)
	at com.android.tools.idea.rendering.RenderService.render(RenderService.java:816)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.doRender(AndroidLayoutPreviewToolWindowManager.java:646)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.access$1700(AndroidLayoutPreviewToolWindowManager.java:82)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7$1.run(AndroidLayoutPreviewToolWindowManager.java:589)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
	at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7.run(AndroidLayoutPreviewToolWindowManager.java:584)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:327)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mehrad-rafigh** [comment]
Could you please post your xml file and your code?

**Comment by MohHeader** [comment]
Same here 
~~~~
<com.rey.material.widget.ListView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/list"
        android:layout_gravity="center_horizontal"
        android:layout_weight="1"
        android:dividerHeight="0dp"/>
~~~~

~~~~
                ListView lv = (ListView) convertView.findViewById(R.id.list);
                final LocationAdapter adapter = new LocationAdapter(getActivity(), Arrays.asList(locations));
                lv.setAdapter(adapter);
                lv.setOnItemClickListener(new AdapterView.OnItemClickListener() {
                    @Override
                    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                        adapter.setSelected(position);
                    }
                });
~~~~

**Comment by rey5137** [comment]
Seem like you don't set value for `android:listSelector` attribute.
