### ISSUE TITLE
Crash when using DatePickerDialog

### ISSUE THREAD

**Issue by hockleongloh** [rey5137/material#451]
Hi, I have encounter following errors when using datepickerdialog.   

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/rey/material/widget/ListView;
                      at com.rey.material.app.DatePickerDialog.onCreate(DatePickerDialog.java:66)
                      at com.rey.material.app.Dialog.init(Dialog.java:176)
                      at com.rey.material.app.Dialog.<init>(Dialog.java:121)
                      at com.rey.material.app.DatePickerDialog.<init>(DatePickerDialog.java:61)
                      at com.rey.material.app.DatePickerDialog$Builder.onBuild(DatePickerDialog.java:812)
                      at com.rey.material.app.Dialog$Builder.build(Dialog.java:1502)
                      at com.rey.material.app.DialogFragment.onCreateDialog(DialogFragment.java:82)
                      at com.rey.material.app.DialogFragment.onCreateDialog(DialogFragment.java:13)
                      at android.support.v4.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:328)
                      at android.support.v4.app.Fragment.performGetLayoutInflater(Fragment.java:1224)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1421)
                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1752)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1821)
                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2595)
                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2382)
                      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2337)
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2244)
                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:702)
                      at android.os.Handler.handleCallback(Handler.java:789)
                      at android.os.Handler.dispatchMessage(Handler.java:98)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6809)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                   Caused by: java.lang.ClassNotFoundException: com.rey.material.widget.ListView
                      at java.lang.VMClassLoader.findLoadedClass(Native Method)
                      at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at com.rey.material.app.DatePickerDialog.onCreate(DatePickerDialog.java:66) 
                      at com.rey.material.app.Dialog.init(Dialog.java:176) 
                      at com.rey.material.app.Dialog.<init>(Dialog.java:121) 
                      at com.rey.material.app.DatePickerDialog.<init>(DatePickerDialog.java:61) 
                      at com.rey.material.app.DatePickerDialog$Builder.onBuild(DatePickerDialog.java:812) 
                      at com.rey.material.app.Dialog$Builder.build(Dialog.java:1502) 
                      at com.rey.material.app.DialogFragment.onCreateDialog(DialogFragment.java:82) 
                      at com.rey.material.app.DialogFragment.onCreateDialog(DialogFragment.java:13) 
                      at android.support.v4.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:328) 
                      at android.support.v4.app.Fragment.performGetLayoutInflater(Fragment.java:1224) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1421) 
                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1752) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1821) 
                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797) 
                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2595) 
                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2382) 
                      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2337) 
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2244) 
                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:702) 
                      at android.os.Handler.handleCallback(Handler.java:789) 
                      at android.os.Handler.dispatchMessage(Handler.java:98) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6809) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
                   Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/widget/ListViewCompat;
                      at com.rey.material.app.DatePickerDialog.onCreate(DatePickerDialog.java:66) 
                      at com.rey.material.app.Dialog.init(Dialog.java:176) 
                      at com.rey.material.app.Dialog.<init>(Dialog.java:121) 
                      at com.rey.material.app.DatePickerDialog.<init>(DatePickerDialog.java:61) 
                      at com.rey.material.app.DatePickerDialog$Builder.onBuild(DatePickerDialog.java:812) 
                      at com.rey.material.app.Dialog$Builder.build(Dialog.java:1502) 
                      at com.rey.material.app.DialogFragment.onCreateDialog(DialogFragment.java:82) 
                      at com.rey.material.app.DialogFragment.onCreateDialog(DialogFragment.java:13) 
                      at android.support.v4.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:328) 
                      at android.support.v4.app.Fragment.performGetLayoutInflater(Fragment.java:1224) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1421) 
                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1752) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1821) 
                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797) 
                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2595) 
                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2382) 
                      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2337) 
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2244) 
                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:702) 
                      at android.os.Handler.handleCallback(Handler.java:789) 
                      at android.os.Handler.dispatchMessage(Handler.java:98) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6809) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.ListViewCompat" on path: DexPathList[[zip file "/data/app/com.nexstream.moveon_android-NfqQMMcsh7cSFpk0bZxROw==/base.apk"],nativeLibraryDirectories=[/data/app/com.nexstream.moveon_android-NfqQMMcsh7cSFpk0bZxROw==/lib/arm64, /data/app/com.nexstream.moveon_android-NfqQMMcsh7cSFpk0bZxROw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at com.rey.material.app.DatePickerDialog.onCreate(DatePickerDialog.java:66) 
                      at com.rey.material.app.Dialog.init(Dialog.java:176) 
                      at com.rey.material.app.Dialog.<init>(Dialog.java:121) 
                      at com.rey.material.app.DatePickerDialog.<init>(DatePickerDialog.java:61) 
                      at com.rey.material.app.DatePickerDialog$Builder.onBuild(DatePickerDialog.java:812) 
                      at com.rey.material.app.Dialog$Builder.build(Dialog.java:1502) 
                      at com.rey.material.app.DialogFragment.onCreateDialog(DialogFragment.java:82) 
                      at com.rey.material.app.DialogFragment.onCreateDialog(DialogFragment.java:13) 
                      at android.support.v4.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:328) 
                      at android.support.v4.app.Fragment.performGetLayoutInflater(Fragment.java:1224) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1421) 
                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1752) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1821) 
                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797) 
                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2595) 
                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2382) 
                      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2337) 
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2244) 
                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:702) 
                      at android.os.Handler.handleCallback(Handler.java:789) 
                      at android.os.Handler.dispatchMessage(Handler.java:98) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6809) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by amjadislam1** [comment]
+1

**Comment by NicolasGodfather** [comment]
+1
