### ISSUE TITLE
 java.lang.NullPointerException on edittext.showDropDown()

### ISSUE THREAD

**Issue by jlccaires** [rey5137/material#58]
I getting null pointer when using edittext.showDropDown() with et_autoCompleteMode="single".
Adapter was set.

**Comment by jlccaires** [comment]
complete stack trace:

 java.lang.NullPointerException
            at android.widget.AbsListView.setSelector(AbsListView.java:1569)
            at android.widget.AutoCompleteTextView.buildDropDown(AutoCompleteTextView.java:1289)
            at android.widget.AutoCompleteTextView.showDropDown(AutoCompleteTextView.java:1140)
            at com.rey.material.widget.EditText.showDropDown(EditText.java:1000)
            at com.mypackage.MyClass$2.onTextChanged(MyClass.java:xx)
            at android.widget.TextView.sendOnTextChanged(TextView.java:6316)
            at android.widget.TextView.handleTextChanged(TextView.java:6357)
            at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:6506)
            at android.text.SpannableStringBuilder.sendTextChange(SpannableStringBuilder.java:889)
            at android.text.SpannableStringBuilder.change(SpannableStringBuilder.java:352)
            at android.text.SpannableStringBuilder.change(SpannableStringBuilder.java:269)
            at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:432)
            at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:409)
            at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:28)
            at android.text.method.QwertyKeyListener.onKeyDown(QwertyKeyListener.java:195)
            at android.text.method.TextKeyListener.onKeyDown(TextKeyListener.java:132)
            at android.widget.TextView.doKeyDown(TextView.java:4454)
            at android.widget.TextView.onKeyDown(TextView.java:4288)
            at android.widget.AutoCompleteTextView.onKeyDown(AutoCompleteTextView.java:746)
            at com.rey.material.widget.EditText$InternalAutoCompleteTextView.superOnKeyDown(EditText.java:3683)
            at com.rey.material.widget.EditText.onKeyDown(EditText.java:2267)
            at com.rey.material.widget.EditText$InternalAutoCompleteTextView.onKeyDown(EditText.java:3612)
            at android.view.KeyEvent.dispatch(KeyEvent.java:1256)
            at android.view.View.dispatchKeyEvent(View.java:3855)
            at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:789)
            at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:789)
            at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:789)
            at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:789)
            at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:789)
            at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:789)
            at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:789)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:1687)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1120)
            at android.app.Dialog.dispatchKeyEvent(Dialog.java:624)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1663)
            at android.view.ViewRoot.deliverKeyEventToViewHierarchy(ViewRoot.java:2560)
            at android.view.ViewRoot.handleFinishedEvent(ViewRoot.java:2535)
            at android.view.ViewRoot.handleMessage(ViewRoot.java:1867)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3683)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by rey5137** [comment]
Seem like you don't set `android:listSelector` atrtibute.

**Comment by jlccaires** [comment]
thanks

**Comment by jlccaires** [comment]
I'm testing on android 2.3
