### ISSUE TITLE
SimpleDialog problem

### ISSUE THREAD

**Issue by gbfansheng** [rey5137/material#60]
((SimpleDialog.Builder)builder).message(message.getFrom()+":"+message.getBody())
                                        .title("Invitation")
                                        .positiveAction("Join")
                                        .negativeAction("Reject")
                                        .contentView(R.layout.invitation_dialog);

If i use the code above,it will crash,logat cat show this:
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
            at android.view.ViewGroup.addViewInner(ViewGroup.java:3547)
            at android.view.ViewGroup.addView(ViewGroup.java:3418)
            at android.view.ViewGroup.addView(ViewGroup.java:3363)
            at android.view.ViewGroup.addView(ViewGroup.java:3339)
            at com.rey.material.app.Dialog.contentView(Dialog.java:546)
            at com.rey.material.app.SimpleDialog.contentView(SimpleDialog.java:115)
            at com.rey.material.app.Dialog.addContentView(Dialog.java:608)
            at com.fan.newlife.MainActivity$2.onBuild(MainActivity.java:168)
            at com.rey.material.app.Dialog$Builder.build(Dialog.java:1020)
            at com.rey.material.app.DialogFragment.onCreateDialog(DialogFragment.java:65)
            at com.rey.material.app.DialogFragment.onCreateDialog(DialogFragment.java:13)
            at android.support.v4.app.DialogFragment.getLayoutInflater(DialogFragment.java:307)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:454)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:153)
            at android.app.ActivityThread.main(ActivityThread.java:5326)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:848)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)
            at dalvik.system.NativeStart.main(Native Method)

But when i use this :
   builder.title("Invitation")
           .positiveAction("Join")
           .negativeAction("Reject")
           .contentView(R.layout.invitation_dialog);

It is ok.

But i couldn't use the propeties of the SimpleDialog.It took me a long time to find out the crash reason.   T_T

**Comment by rey5137** [comment]
When you call `message(String)` method, it already added a TextView as content view, so your next call on `contentView(int)` give that exception. Use `message()` method when you want to display a simple message dialog, if you want to use a custom view, you should use only `contentView()`.

**Comment by gbfansheng** [comment]
Thanks a lot.
The exception info was strange and confused me.
