### ISSUE TITLE
Demo application crashes

### ISSUE THREAD

**Issue by ZieIony** [rey5137/Material#7]
The demo application crashes in dialogs tab, after clicking [DATE (LIGHT)]

Device: Samsung Galaxy S, Android 2.3

    E/AndroidRuntime( 1858): java.lang.ArrayIndexOutOfBoundsException
    E/AndroidRuntime( 1858):        at com.rey.material.widget.DatePicker$MonthView.onDraw(DatePicker.java:547)
    E/AndroidRuntime( 1858):        at android.view.View.draw(View.java:6933)
    E/AndroidRuntime( 1858):        at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
    E/AndroidRuntime( 1858):        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
    E/AndroidRuntime( 1858):        at android.widget.AbsListView.dispatchDraw(AbsListView.java:1604)
    E/AndroidRuntime( 1858):        at android.widget.ListView.dispatchDraw(ListView.java:3210)
    E/AndroidRuntime( 1858):        at android.support.v7.internal.widget.ListViewCompat.dispatchDraw(ListViewCompat.java:102)
    E/AndroidRuntime( 1858):        at android.view.View.draw(View.java:6936)
    E/AndroidRuntime( 1858):        at android.widget.AbsListView.draw(AbsListView.java:3022)
    E/AndroidRuntime( 1858):        at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
    E/AndroidRuntime( 1858):        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
    E/AndroidRuntime( 1858):        at android.view.View.draw(View.java:6936)
    E/AndroidRuntime( 1858):        at android.widget.FrameLayout.draw(FrameLayout.java:357)
    E/AndroidRuntime( 1858):        at com.rey.material.app.DatePickerDialog$DatePickerLayout.draw    (DatePickerDialog.java:540

**Comment by rey5137** [comment]
Fixed. The cause is incorrect index shifting when draw label on MonthView.

**Comment by yaadm** [comment]
*****************************************************
doing:
*****************************************************

DatePickerDialog datePickerDialog = new DatePickerDialog(getActivity());

				datePickerDialog.onDateChangedListener(new DatePickerDialog.OnDateChangedListener() {
                    @Override
                    public void onDateChanged(int i, int i1, int i2, int i3, int i4, int i5) {

                        LogUtils.d(TAG, "", "i = " + i);
                        LogUtils.d(TAG, "", "i1 = " + i1);
                        LogUtils.d(TAG, "", "i2 = " + i2);
                        LogUtils.d(TAG, "", "i3 = " + i3);
                        LogUtils.d(TAG, "", "i4= " + i4);
                        LogUtils.d(TAG, "", "i5 = " + i5);

                    }
                });

                datePickerDialog.show();

*****************************************************
results in
*****************************************************

06-01 16:23:28.235  27301-27301/com.objective.socialreminder E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.objective.socialreminder, PID: 27301
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
            at android.view.GLES20Canvas.drawText(GLES20Canvas.java:918)
            at com.rey.material.widget.DatePicker$MonthView.onDraw(DatePicker.java:563)
            at android.view.View.draw(View.java:15114)
            at android.view.View.updateDisplayListIfDirty(View.java:14048)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.widget.ListView.drawChild(ListView.java:3396)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.widget.AbsListView.dispatchDraw(AbsListView.java:2596)
            at android.widget.ListView.dispatchDraw(ListView.java:3391)
            at android.support.v7.internal.widget.ListViewCompat.dispatchDraw(ListViewCompat.java:102)
            at android.view.View.draw(View.java:15117)
            at android.widget.AbsListView.draw(AbsListView.java:4085)
            at android.view.View.updateDisplayListIfDirty(View.java:14048)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.draw(View.java:15117)
            at android.widget.FrameLayout.draw(FrameLayout.java:592)
            at com.rey.material.app.DatePickerDialog$DatePickerLayout.draw(DatePickerDialog.java:609)
            at android.view.View.updateDisplayListIfDirty(View.java:14048)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.draw(View.java:15117)
            at android.widget.FrameLayout.draw(FrameLayout.java:592)
            at com.rey.material.app.Dialog$DialogCardView.draw(Dialog.java:1285)
            at android.view.View.updateDisplayListIfDirty(View.java:14048)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14043)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14043)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14043)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.draw(View.java:15117)
            at android.widget.FrameLayout.draw(FrameLayout.java:592)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2850)
            at android.view.View.updateDisplayListIfDirty(View.java:14048)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:266)
            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:272)
            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:311)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2499)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2337)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1968)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5786)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android
