### ISSUE TITLE
Defining Support Mode for EditText is throwing inflation Exception

### ISSUE THREAD

**Issue by kbakhit** [rey5137/material#70]
Hi,

I'm facing an issue. When I define; app:et_supportMode attribute in EditText, the layout XML fails to inflate.

The XML code:

<com.rey.material.widget.EditText
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/editText"
        android:hint="Write your name"
        android:layout_margin="10dp"
        android:layout_marginTop="3dp"
        android:layout_marginBottom="0dp"
        android:singleLine="true"
        app:et_inputId="@+id/editText1"
        app:et_labelEnable="true"
        app:et_dividerColor="@color/black"
        app:et_dividerErrorColor="@color/red"
        app:et_dividerHeight="1dp"
        app:et_error="ET error"
        app:et_supportMode="helperWithError"
        />

Error output:
Caused by: android.view.InflateException: Binary XML file line #33: Error inflating class com.rey.material.widget.EditText
            at android.view.LayoutInflater.createView(LayoutInflater.java:620)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
            at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
            at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
            at android.view.LayoutInflater.inflate(Native Method)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
            at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:228)
            at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)

If I remove the " app:et_supportMode" definition, the layout inflates successfully.

**Comment by ujvl** [comment]
+1, facing the same issue

**Comment by brunano21** [comment]
I have the same problem!

**Comment by lvl4fi4** [comment]
I think you didn't import the library properly. i don't face this problem.
i suggest you started from the beginning , just run the demo app if you didn't done yet and see if you facing this problem.

**Comment by GunaseelanArumaikkannu** [comment]
For me also same problem!

**Comment by lvl4fi4** [comment]
@GunaseelanArumaikkannu :
use this http://qfs.mobi/f2618942 project as module import instead of using `gradle` version  till @rey5137 come back and fix this. 
also need to copy `string.xml , thems.xml etc...`  from demo app project to your project to fix.
